version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit
workflows:
  build_and_test:
    jobs:
      - build