<?php

declare (strict_types = 1);

namespace ReallifeKip\ImmutableBase\Internal;

use Closure;
use ReallifeKip\ImmutableBase\Attributes\ArrayOf;
use ReallifeKip\ImmutableBase\Attributes\Defaults;
use ReallifeKip\ImmutableBase\Attributes\InputKeyTo;
use ReallifeKip\ImmutableBase\Attributes\KeepOnNull;
use ReallifeKip\ImmutableBase\Attributes\Lax;
use ReallifeKip\ImmutableBase\Attributes\OutputKeyTo;
use ReallifeKip\ImmutableBase\Attributes\SkipOnNull;
use ReallifeKip\ImmutableBase\Attributes\Spec;
use ReallifeKip\ImmutableBase\Attributes\Strict;
use ReallifeKip\ImmutableBase\Attributes\ValidateFromSelf;
use ReallifeKip\ImmutableBase\BasicTrait;
use ReallifeKip\ImmutableBase\Enums\KeyCase;
use ReallifeKip\ImmutableBase\Enums\Native;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidArrayOfTargetException;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidArrayOfUsageException;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidKeyCaseException;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidPropertyTypeException;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidSpecException;
use ReallifeKip\ImmutableBase\Exceptions\DefinitionExceptions\InvalidVisibilityException;
use ReallifeKip\ImmutableBase\ImmutableBase;
use ReallifeKip\ImmutableBase\Objects\DataTransferObject;
use ReallifeKip\ImmutableBase\Objects\SingleValueObject;
use ReallifeKip\ImmutableBase\Types;
use ReflectionClass;
use ReflectionNamedType;
use ReflectionProperty;
use ReflectionUnionType;

/**
 * Turns class declarations into compiled metadata: reflects properties and
 * attributes (or restores a still-valid cache entry), enforces the
 * definition rules (visibility, forbidden types, #[ArrayOf] usage, key
 * cases), compiles each property through Resolver and builds the readonly
 * hydrator. Runs once per class per process; results live in Metadata.
 *
 * @internal Not part of the public API; may change without notice.
 *
 * @phpstan-import-type Hydrator from Types
 * @phpstan-import-type NamedTypeFromUnion from Types
 * @phpstan-import-type NamedType from Types
 * @phpstan-import-type UnionType from Types
 * @phpstan-import-type Type from Types
 * @phpstan-import-type Property from Types
 * @phpstan-import-type Caches from Types
 */
final class Scanner
{
    use BasicTrait;

    /**
     * Compiles metadata for $object's class and every ancestor below
     * ImmutableBase: walks the class hierarchy upward,
     * scanning and compiling property metadata for each ancestor that hasn't
     * been processed yet. Supports three metadata sources:
     *
     *   1. Compiled metadata — already registered (skip via continue)
     *   2. Cached metadata — pre-generated by ib-cacher (restore validate method),
     *      used only while it still matches the class (see cacheMatchesClass())
     *   3. Reflection — full scan via scanProperties()
     *
     * After metadata is resolved, each property type is compiled by
     * Internal\Resolver::compile() and the class gets a hydrator closure for
     * readonly assignment.
     *
     * @param ImmutableBase $object The instance being constructed; used to seed ReflectionClass and determine DTO/VO/SVO type.
     * @throws InvalidSpecException
     * @throws InvalidVisibilityException
     * @throws InvalidArrayOfTargetException
     * @throws InvalidArrayOfUsageException
     * @return Caches
     */
    public static function compile(ImmutableBase $object): array
    {
        $self = ImmutableBase::class;
        for ($ref = Metadata::reflection($object::class); $ref && $ref->name !== $self; $ref = $ref->getParentClass()) {
            $classname = $ref->name;
            if (Metadata::has($classname)) {
                continue;
            }
            if (($cached = Metadata::cached($classname)) !== null && self::cacheMatchesClass($cached, $ref)) {
                $props                   = $cached;
                $props['validateMethod'] = !$props['hasValidate'] ?: $ref->getMethod('validate');
            } else {
                $props = self::scanProperties(
                    $ref,
                    match (true) {
                        $object instanceof DataTransferObject => [true, false, false],
                        $object instanceof SingleValueObject  => [false, true, true],
                        default                               => [false, true, false]
                    }
                );
            }
            $props['types']    = array_map(Resolver::compile(...), $props['types']);
            $props['hydrator'] = self::createHydrator($classname, array_keys($props['types']));
            Metadata::put($classname, $props);
        }

        return Metadata::all();
    }

    /**
     * Whether a pre-generated cache entry still describes $ref: the same
     * property names, each with the same declared type and nullability.
     * A class edited after ib-cacher ran (a property added, removed, renamed
     * or retyped) fails the check and is scanned by reflection instead, so a
     * stale cache degrades to the uncached path rather than to wrong
     * metadata. Changes to attributes or methods alone are not detected.
     *
     * @param Property $cached
     */
    private static function cacheMatchesClass(array $cached, ReflectionClass $ref): bool
    {
        $properties = $ref->getProperties();
        if (\count($properties) !== \count($cached['types'])) {
            return false;
        }
        foreach ($properties as $property) {
            $type  = $property->getType();
            $entry = $cached['types'][$property->name] ?? null;
            if (
                $type === null || $entry === null
                || $entry['allowsNull'] !== $type->allowsNull()
                || $entry['typename']['string'] !== ($type instanceof ReflectionNamedType ? $type->getName() : (string) $type)
            ) {
                return false;
            }
        }

        return true;
    }

    /**
     * Reflects all public properties of a class and assembles the full
     * property metadata structure. Extracts class-level attributes (#[Strict],
     * #[Lax], #[SkipOnNull], #[ValidateFromSelf], #[Spec], #[InputKeyTo],
     * #[OutputKeyTo]) and builds the validation lineage via classTree for
     * enforceValidationRules(). Also collects per-property InputKeyTo overrides
     * into `propertyInputKeyCases` for use by KeyCaser::remapInput().
     *
     * @param ReflectionClass $ref The class to scan.
     * @param array{bool, bool, bool} $flags Tuple of [isDTO, isVO, isSVO] indicating the object's base type.
     * @throws InvalidSpecException
     * @return Property
     */
    private static function scanProperties(ReflectionClass $ref, array $flags): array
    {
        [$isDTO, $isVO, $isSVO] = $flags;
        $classname              = $ref->name;
        if (!$isDTO && $ref->getAttributes(Spec::class)) {
            $spec = self::getAttributeArgument($ref, Spec::class);
            if (!\is_string($spec) || empty($spec = mb_trim($spec))) {
                throw new InvalidSpecException($classname);
            }
        }
        $hasValidate     = $isDTO ? false : $ref->hasMethod('validate');
        $hasPrepareInput = $ref->hasMethod('prepareInput') && $ref->getMethod('prepareInput')->getDeclaringClass()->name === $classname;
        $classTree       = [$classname => $classname] + class_parents($classname);
        $prop            = [
            'ref'               => $ref,
            'name'              => $classname,
            'isStrict'          => $ref->getAttributes(Strict::class) !== [],
            'isLax'             => $ref->getAttributes(Lax::class) !== [],
            'isDTO'             => $isDTO,
            'isVO'              => $isVO,
            'isSVO'             => $isSVO,
            'validateFromSelf'  => $ref->getAttributes(ValidateFromSelf::class) !== [],
            'skipOnNull'        => $ref->getAttributes(SkipOnNull::class) !== [],
            'hasValidate'       => $hasValidate,
            'hasPrepareInput'   => $hasPrepareInput,
            'validateMethod'    => $hasValidate ? $ref->getMethod('validate') : false,
            'spec'              => $spec ?? null,
            'classTree'         => $classTree,
            'classTreeReversed' => array_reverse($classTree),
            'inputKeyCase'      => self::getValidatedKeyCase(self::getAttributeArgument($ref, InputKeyTo::class), 'InputKeyTo', "$classname::class"),
            'types'             => [],
        ];
        $obj      = null;
        $defaults = [];
        if (!$ref->isAbstract()) {
            /** @var ImmutableBase $obj */
            $obj      = $ref->newInstanceWithoutConstructor();
            $defaults = $obj::defaultValues();
        }
        $classOutputKeyCase = self::getValidatedKeyCase(self::getAttributeArgument($ref, OutputKeyTo::class), 'OutputKeyTo', "$classname::class");
        foreach ($ref->getProperties() as $property) {
            $name                 = $property->name;
            $prop['types'][$name] = self::scanProperty($property, $prop['skipOnNull'], $classOutputKeyCase);
            $default              = match (true) {
                $obj === null                       => null,
                \array_key_exists($name, $defaults) => $defaults[$name],
                default                             => self::getAttributeArgument($property, Defaults::class)
            };
            if ($default !== null) {
                $prop['types'][$name]['defaults'] = $default;
            }
        }
        foreach ($prop['types'] as $name => $type) {
            if ($type['hasInputKeyOverride']) {
                $propInputKeyCases[$name] = $type['inputKeyCase'];
            }
        }
        $prop['propertyInputKeyCases'] = $propInputKeyCases ?? null;

        return $prop;
    }

    /**
     * Extracts type metadata from a single property. Enforces that all
     * properties must be public (readonly is implicit via the class declaration).
     * Delegates to scanNamedType() or scanUnionType() based on reflection type,
     * and resolves #[ArrayOf], #[SkipOnNull], #[KeepOnNull], #[InputKeyTo],
     * #[OutputKeyTo] attributes. Property-level #[InputKeyTo] stores the target
     * KeyCase in `inputKeyCase`; combined with `hasInputKeyOverride`, this is
     * picked up by scanProperties() for KeyCaser::remapInput(). Property-level
     * #[OutputKeyTo] (falling back to the class-level case) pre-computes `outputKey`.
     *
     * @param ReflectionProperty $property         The property to extract metadata from.
     * @param bool               $classSkipOnNull  Whether the owning class has a class-level #[SkipOnNull] attribute.
     * @param KeyCase|null       $classOutputKeyCase Class-level OutputKeyTo case, used when the property has none.
     * @throws InvalidVisibilityException
     * @return Type
     */
    private static function scanProperty(ReflectionProperty $property, bool $classSkipOnNull, ?KeyCase $classOutputKeyCase = null): array
    {
        if (!$property->isPublic()) {
            throw new InvalidVisibilityException($property->name);
        }
        $type    = $property->getType();
        $name    = $property->name;
        $target  = $property->getDeclaringClass()->getName() . "::$$name";
        $inCase  = self::getValidatedKeyCase(self::getAttributeArgument($property, InputKeyTo::class), 'InputKeyTo', $target);
        $outCase = self::getValidatedKeyCase(self::getAttributeArgument($property, OutputKeyTo::class), 'OutputKeyTo', $target) ?? $classOutputKeyCase;

        return [
            'ref'                 => $type,
            'propertyRef'         => $property,
            'allowsNull'          => $type->allowsNull(),
            'arrayOf'             => self::resolveArrayOf($property, $type),
            'propertyName'        => $name,
            'inputKeyCase'        => $inCase,
            'hasInputKeyOverride' => $inCase !== null,
            'outputKey'           => $outCase !== null ? KeyCaser::convert($name, $outCase) : $name,
            'skipOnNull'          => $classSkipOnNull || $property->getAttributes(SkipOnNull::class) !== [],
            'keepOnNull'          => $property->getAttributes(KeepOnNull::class) !== [],
            'isUnion'             => !($type instanceof ReflectionNamedType),
        ] + ($type instanceof ReflectionNamedType ? self::scanNamedType($type) : self::scanUnionType($type));
    }

    /**
     * Validates and resolves the #[ArrayOf] attribute on a property.
     * Each target class must be an ImmutableBase descendant or Native scalar.
     * The property type must be exactly `array` (not a union or any other type).
     *
     * @param ReflectionProperty $property The property to inspect for #[ArrayOf].
     * @param ReflectionNamedType|ReflectionUnionType $refType The property's declared type, used to enforce the `array` constraint.
     * @throws InvalidArrayOfTargetException
     * @throws InvalidArrayOfUsageException
     * @return list<non-empty-string>|null
     */
    private static function resolveArrayOf(ReflectionProperty $property, ReflectionNamedType | ReflectionUnionType $refType): ?array
    {
        $args = self::getAttributeArgument($property, ArrayOf::class, false);
        if ($args === null) {
            return null;
        }
        if ($args === []) {
            throw new InvalidArrayOfTargetException();
        }
        if ($refType instanceof ReflectionUnionType) {
            throw new InvalidArrayOfUsageException($property->name, (string) $refType);
        }
        if ($refType->getName() !== 'array') {
            throw new InvalidArrayOfUsageException($property->name, (string) $refType);
        }
        foreach ($args as $arg) {
            $resolved[] = match (true) {
                $arg instanceof Native         => $arg->value,
                enum_exists($arg)              => $arg,
                !is_a($arg, ImmutableBase::class, true) => throw new InvalidArrayOfTargetException(),
                default                        => $arg,
            };
        }

        return $resolved;
    }

    /**
     * Validates that a value resolved from #[InputKeyTo] or #[OutputKeyTo] is
     * either null (attribute absent) or a KeyCase enum instance.
     *
     * @param mixed  $value     The raw attribute argument.
     * @param string $attribute Short attribute name ('InputKeyTo' or 'OutputKeyTo').
     * @param string $target    Human-readable scan location for the exception message.
     * @throws InvalidKeyCaseException
     */
    private static function getValidatedKeyCase(mixed $value, string $attribute, string $target): ?KeyCase
    {
        if ($value !== null && !($value instanceof KeyCase)) {
            throw new InvalidKeyCaseException($value, $attribute, $target);
        }

        return $value;
    }

    /**
     * Scans a single named type, enforcing the forbidden type rule:
     * `object`, `iterable`, non-ImmutableBase classes, and non-enum classes are rejected at
     * definition time via InvalidPropertyTypeException. Standalone `null` passes through
     * here (as a builtin) and is rejected later in Internal\Resolver::compile().
     *
     * When called for a top-level property ($fromUnion=false), also resolves
     * whether the type is an SVO (recorded in the metadata). Union members
     * skip this; their matchers are chosen by type name in Internal\Resolver.
     *
     * @param ReflectionNamedType $refType The named type to scan and validate.
     * @throws InvalidPropertyTypeException
     * @return NamedType|NamedTypeFromUnion
     */
    private static function scanNamedType(ReflectionNamedType $refType, bool $fromUnion = false): array
    {
        $typename  = $refType->getName();
        $isBuiltin = $refType->isBuiltin();
        $isEnum    = !$isBuiltin && enum_exists($typename);
        if ($typename === 'object' || $typename === 'iterable' || (!$isBuiltin && !is_a($typename, ImmutableBase::class, true) && !$isEnum)) {
            throw new InvalidPropertyTypeException($typename);
        }
        $result = [
            'typename'  => [
                'string' => $typename,
                'array'  => [$typename],
            ],
            'isBuiltin' => $isBuiltin,
            'isEnum'    => $isEnum,
        ];
        if (!$fromUnion) {
            $compiled        = Metadata::get($typename);
            $result['isSVO'] = $compiled ? $compiled['isSVO'] : (!$isBuiltin && is_a($typename, SingleValueObject::class, true));
        }

        return $result;
    }

    /**
     * Scans a union type by delegating each member to scanNamedType().
     * PHP does not allow nested unions, so each member is guaranteed to be
     * a ReflectionNamedType. Members are scanned with $fromUnion=true to
     * skip isSVO resolution (matchers are chosen by type name in Internal\Resolver).
     *
     * @param ReflectionUnionType $refType The union type whose members will be individually scanned.
     * @return UnionType
     */
    private static function scanUnionType(ReflectionUnionType $refType): array
    {
        $unionTypes = $refType->getTypes();

        return [
            'typename' => [
                'string' => (string) $refType,
                'array'  => array_map(static fn(ReflectionNamedType $type): string => $type->getName(), $unionTypes),
            ],
            'types'    => array_map(static fn(ReflectionNamedType $type) => self::scanNamedType($type, true), $unionTypes),
        ];
    }

    /**
     * Creates a Closure bound to the target class scope, enabling direct
     * assignment to readonly properties. This bypasses the readonly restriction
     * because the closure operates within the declaring class's scope.
     *
     * @param class-string $classname The declaring class; the closure is bound to this scope.
     * @param list<string> $propertyNames Property names to assign during hydration.
     * @return Hydrator
     */
    private static function createHydrator(string $classname, array $propertyNames): Closure
    {
        return Closure::bind(
            static function (ImmutableBase $obj, array $resolved) use ($propertyNames): void {
                foreach ($propertyNames as $name) {
                    $obj->$name = $resolved[$name];
                }
            },
            null,
            $classname
        );
    }
}
