name: CI

on:
  push:
    branches: [main, v3.0.0-rc]
  pull_request:
    branches: [main, v3.0.0-rc]

jobs:
  test:
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml --coverage-text

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: phpunit
          fail_ci_if_error: true

  FOSSA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run FOSSA scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}

  SONAR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=ReallifeKip_ImmutableBase
            -Dsonar.organization=reallifekip
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
